apiVersion: kagent.dev/v1alpha2
kind: ModelConfig
metadata:
  name: byo-model
  namespace: kagent
spec:
  apiKeySecret: empyty-secret
  apiKeySecretKey: OPENAI_API_KEY
  model: google/gemma-3-1b
  provider: OpenAI
  openAI:
    baseUrl: "http://10.52.33.69:1234/v1"
