apiVersion: kagent.dev/v1alpha2
kind: ModelConfig
metadata:
  name: gpt-oss-120tog
  namespace: kagent
spec:
  apiKeySecretKey: OPENAI_API_KEY
  apiKeySecret: kagent-openai
  model: gpt-oss:120b
  provider: Ollama
  ollama:
    host: <PATH>


